### ISSUE TITLE
Error in src/heterophilic_graphs/models.py

### ISSUE THREAD

**Issue by viktor-ktorvi** [tk-rusch/GraphCON#5]
Hi,

In [file](https://github.com/tk-rusch/GraphCON/blob/main/src/heterophilic_graphs/models.py), there are errors in lines 64 where it should be `self.gamma = gamma` instead of `self.alpha = gamma`, as well as in line 90 where it should be `for i in range(self.nlayers):` instead of `for i in range(self.N):`, if I'm not wrong.

Kind regards 👍

**Comment by tk-rusch** [comment]
Hi
Thanks for bringing this to our attention. You are right -- they are clearly typos (incorrect copy/paste from an old version). 

Best,
Konstantin
